# Generated by Django 5.0.3 on 2024-03-14 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_vision', models.JSONField()),
                ('Note', models.CharField(max_length=700)),
                ('information', models.CharField(max_length=700)),
            ],
            options={
                'db_table': 'Dots',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('password', models.CharField(max_length=75)),
                ('is_superuser', models.BooleanField()),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('tg_username', models.CharField(max_length=75)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateTimeField()),
                ('date_out', models.DateTimeField()),
                ('comment', models.CharField(max_length=700)),
                ('baggage', models.CharField(max_length=3000)),
                ('note', models.CharField(max_length=700)),
                ('rate', models.IntegerField()),
                ('dots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutun_app.dot')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutun_app.user')),
            ],
            options={
                'db_table': 'Routes',
            },
        ),
    ]
