# Generated by Django 5.0.3 on 2024-03-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutun_app', '0002_alter_route_author_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dot',
            old_name='Note',
            new_name='note',
        ),
    ]
