# Generated by Django 5.0.3 on 2024-03-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutun_app', '0003_rename_note_dot_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='Name',
            field=models.CharField(default='Untitled', max_length=125),
        ),
    ]
