# Generated by Django 5.0.3 on 2024-03-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutun_app', '0004_route_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dot',
            name='name',
            field=models.CharField(default='Untitled dot', max_length=125),
        ),
    ]
