# Generated by Django 5.0.3 on 2024-03-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutun_app', '0005_dot_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='rate',
            field=models.IntegerField(default='-1'),
        ),
    ]
