# Generated by Django 5.0.3 on 2024-03-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutun_app', '0006_alter_route_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='dots',
        ),
        migrations.AddField(
            model_name='route',
            name='dots',
            field=models.ManyToManyField(to='tutun_app.dot'),
        ),
    ]
