# Generated by Django 5.0.3 on 2024-03-18 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutun_app', '0007_remove_route_dots_route_dots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route_for_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Untitled', max_length=125)),
                ('comment', models.CharField(max_length=700)),
                ('rate', models.IntegerField(default='-1')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dots', models.ManyToManyField(to='tutun_app.dot')),
            ],
            options={
                'db_table': 'Routes_for_list',
            },
        ),
    ]
