# Generated by Django 5.0.3 on 2024-03-18 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutun_app', '0008_route_for_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateDot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled dot', max_length=125)),
                ('api_vision', models.JSONField()),
                ('note', models.CharField(max_length=700)),
                ('information', models.CharField(max_length=700)),
            ],
            options={
                'db_table': 'Private_Dots',
            },
        ),
        migrations.CreateModel(
            name='PublicDot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled dot', max_length=125)),
                ('api_vision', models.JSONField()),
                ('information', models.CharField(max_length=700)),
            ],
            options={
                'db_table': 'Public_Dots',
            },
        ),
        migrations.RemoveField(
            model_name='route_for_list',
            name='dots',
        ),
        migrations.RemoveField(
            model_name='route',
            name='dots',
        ),
        migrations.RemoveField(
            model_name='route',
            name='author',
        ),
        migrations.RemoveField(
            model_name='route_for_list',
            name='author',
        ),
        migrations.CreateModel(
            name='PrivateRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Untitled', max_length=125)),
                ('date_in', models.DateTimeField()),
                ('date_out', models.DateTimeField()),
                ('comment', models.CharField(max_length=700)),
                ('baggage', models.CharField(max_length=3000)),
                ('note', models.CharField(max_length=700)),
                ('rate', models.IntegerField(default='-1')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dots', models.ManyToManyField(to='tutun_app.privatedot')),
            ],
            options={
                'db_table': 'Private_Routes',
            },
        ),
        migrations.CreateModel(
            name='PublicRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Untitled', max_length=125)),
                ('comment', models.CharField(max_length=700)),
                ('rate', models.IntegerField(default='-1')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dots', models.ManyToManyField(to='tutun_app.publicdot')),
            ],
            options={
                'db_table': 'Public_Routes',
            },
        ),
        migrations.DeleteModel(
            name='Dot',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Route_for_list',
        ),
    ]
