# Generated by Django 5.0.3 on 2024-03-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutun_app', '0009_privatedot_publicdot_remove_route_for_list_dots_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Notes',
            },
        ),
        migrations.RemoveField(
            model_name='privateroute',
            name='note',
        ),
        migrations.AddField(
            model_name='privateroute',
            name='note',
            field=models.ManyToManyField(to='tutun_app.note'),
        ),
    ]
