# Generated by Django 5.0.3 on 2024-05-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutun_app', '0012_publicroute_length_publicroute_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='privatedot',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='privateroute',
            name='date_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='privateroute',
            name='date_out',
            field=models.DateField(),
        ),
    ]
