# Generated by Django 5.0.3 on 2024-05-17 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutun_app', '0013_alter_complaint_data_alter_privatedot_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatedot',
            name='api_vision',
        ),
        migrations.RemoveField(
            model_name='publicdot',
            name='api_vision',
        ),
    ]
